### ISSUE TITLE
Proof of reserves UI fixes

### ISSUE THREAD

**Issue by AugustoLara** [hashed-io/hashed.network#57]
- [x] Should say: There are no vaults yet

![Image](https://user-images.githubusercontent.com/7217054/228097466-b61f1c43-9f6c-414f-8588-c8157eb4e724.png)

- [x] If you don't have an xpub you can't create a vault so if you don't have one, instead of showing the message above it should say: You and all the cosigners will need an xpub to use Bitcoin Vaults. Xpubs are created and managed under Extended Keys.
- [x] The screen below that shows when trying to login from an account without HASH, instead of taking you to contact us should take you to the HASH purchase screen that Armando is working on.

![Image](https://user-images.githubusercontent.com/7217054/228100111-c7516052-1883-4601-9f1f-7195199dccd7.png)

- [ ]

**Comment by jmgayosso** [comment]
> * If you don't have an xpub you can't create a vault so if you don't have one, instead of showing the message above it should say: You and all the cosigners will need an xpub to use Bitcoin Vaults. Xpubs are created and managed under Extended Keys.

Where do you see this message? I can not find a match coincidence
